# This python programme can automate our data cleaning task of excel csv files.

In [1]:
import pandas as pd
from datetime import datetime

def data_cleaning(path):
    file = pd.read_csv(path, index_col=None)
    file = file.drop_duplicates()
    file = file.dropna()
    return file

In [50]:
# 2021_06_divvy_tripdata.csv
data_cleaning('C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202106-divvy-tripdata.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
50,0D904FEC5F84A538,classic_bike,2021-06-04 07:29:18,2021-06-04 07:45:34,Orleans St & Elm St,TA1306000006,Orleans St & Elm St,TA1306000006,41.902924,-87.637715,41.902924,-87.637715,member
51,C4185F300D6B552B,classic_bike,2021-06-23 08:39:36,2021-06-23 08:41:37,Desplaines St & Kinzie St,TA1306000003,Kingsbury St & Kinzie St,KA1503000043,41.888716,-87.644448,41.889177,-87.638506,member
53,60F97090AC85F55E,classic_bike,2021-06-27 12:26:58,2021-06-27 12:34:45,Clark St & Grace St,TA1307000127,Clark St & Leland Ave,TA1309000014,41.950780,-87.659172,41.967096,-87.667429,member
56,FBC7B1F0160AA304,classic_bike,2021-06-01 12:30:24,2021-06-01 12:33:02,Kingsbury St & Kinzie St,KA1503000043,Desplaines St & Kinzie St,TA1306000003,41.889177,-87.638506,41.888716,-87.644448,member
57,37A52001AEEFA4E5,classic_bike,2021-06-01 11:32:17,2021-06-01 11:34:43,Desplaines St & Kinzie St,TA1306000003,Kingsbury St & Kinzie St,KA1503000043,41.888716,-87.644448,41.889177,-87.638506,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
729578,03087E3FF2C31427,classic_bike,2021-06-11 13:40:19,2021-06-11 13:54:39,Clark St & Chicago Ave,13303,Kingsbury St & Kinzie St,KA1503000043,41.896750,-87.630890,41.889177,-87.638506,casual
729580,6C9A65BFB41FD57C,classic_bike,2021-06-26 22:55:05,2021-06-26 23:04:38,Wells St & Polk St,SL-011,Kingsbury St & Kinzie St,KA1503000043,41.872596,-87.633502,41.889177,-87.638506,casual
729586,32D8203CE17F0348,electric_bike,2021-06-26 22:54:11,2021-06-26 23:04:47,Wells St & Polk St,SL-011,Kingsbury St & Kinzie St,KA1503000043,41.872602,-87.633845,41.889037,-87.638070,casual
729591,47BD346FAFB9BE6D,classic_bike,2021-06-30 17:35:10,2021-06-30 17:43:20,Clark St & Chicago Ave,13303,Kingsbury St & Kinzie St,KA1503000043,41.896750,-87.630890,41.889177,-87.638506,member
729592,52467C23D17C6AFE,classic_bike,2021-06-13 19:24:30,2021-06-13 19:34:11,Indiana Ave & 26th St,TA1307000005,State St & 19th St,SL-013,41.845687,-87.622481,41.856594,-87.627542,member

In [51]:
data_frame = data_cleaning('C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202106-divvy-tripdata.csv')
type(data_frame['started_at'])

pandas.core.series.Series

In [2]:
def save_data(source_path, destination_path):
    df = data_cleaning(source_path)
    df.to_csv(destination_path, index=None)

In [53]:
# 202106-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202106-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_06_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [54]:
# 202107-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202107-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_07_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [55]:
# 202108-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202108-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_08_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [56]:
# 202109-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202109-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_09_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [57]:
# 202110-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202110-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_10_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [58]:
# 202111-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202111-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_11_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [59]:
# 202112-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202112-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_12_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [60]:
# 202201-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202201-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2022_01_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [61]:
# 202202-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202202-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2022_02_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [62]:
# 202203-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202203-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2022_03_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [63]:
# 202204-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202204-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2022_04_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [64]:
# 202205-divvy-tripdata.csv
source_path = 'C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Case Study 1 How Does a Bike-Share Navigate Speedy Success\\Data\\202205-divvy-tripdata.csv'
destination_path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2022_05_divvy_tripdata_cleaned.csv"
save_data(source_path, destination_path)

In [8]:
import pandas as pd
import glob

# getting excel files to be merged from the Desktop 
path = "C:\Users\Dell\Downloads\Google Data Analytics Professional Course\Course - 8 Google Data Analytics Capstone Complete a Case Study\Cyclistic Bikeshare Data"

# read all the files with extension .xlsx i.e. excel 
filenames = glob.glob(path + "\*.csv")
print('File names:', filenames)

# empty data frame for the new output excel file with the merged excel files
output_csv = pd.DataFrame()

# for loop to iterate all excel files
for file in filenames:
    # using concat for excel files
    # after reading them with read_excel()
    df = pd.concat(pd.read_excel( file, sheet_name=None), ignore_index=True, sort=False)
    # appending data of excel files
    output_csv = output_csv.append( df, ignore_index=True)

print('Final Excel sheet now generated at the same location:')
output_csv.to_csv("C:/Users/Dell/Downloads/Google Data Analytics Professional Course/Course - 8 Google Data Analytics Capstone Complete a Case Study/Cyclistic Bikeshare Data/Output.xlsx", index=False)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3174562901.py, line 5)

In [ ]:
path = "C:\\Users\\Dell\\Downloads\\Google Data Analytics Professional Course\\Course - 8 Google Data Analytics Capstone Complete a Case Study\\Cyclistic Bikeshare Data\\2021_06_divvy_tripdata_cleaned.csv"

In [3]:
final_df.to_csv("C:\\Users\\Dell\\final_dataframe.csv")

In [3]:
import pandas as pd
pd.read_csv("C:\\Users\\Dell\\region.csv", skiprows=1, header= None)

             0             1
0            1      New York
1            2        Dallas
2            3   Los Angeles
3            4       Chicago
4            5  Philadelphia
...        ...           ...
100168   99996       Chicago
100169   99997      New York
100170   99998     San Diego
100171   99999       Chicago
100172  100000        Dallas

[100173 rows x 2 columns]